server:
  port: 8098 # 访问端口
  servlet:
    session:
      timeout: 3600s
    context-path: /

mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      table-prefix: t_
      id-type: UUID
logging:
  level:
    springfox: 'off'
    liquibase: 'off'
    org.springframework.context.support: 'off'
  config: classpath:logback-spring.xml
